import { FilterOption, SortOption } from '../types/WalkerMatchingScreen';

export const FILTER_OPTIONS: FilterOption[] = [
  { value: 'all', label: '전체', count: 0 },
  { value: 'available', label: '예약 가능', count: 0 },
  { value: 'high_rating', label: '높은 평점', count: 0 },
  { value: 'nearby', label: '가까운 거리', count: 0 },
  { value: 'experienced', label: '경험 많은', count: 0 },
  { value: 'certified', label: '자격증 보유', count: 0 },
];

export const SORT_OPTIONS: SortOption[] = [
  { value: 'rating', label: '평점순' },
  { value: 'distance', label: '거리순' },
  { value: 'price', label: '가격순' },
  { value: 'experience', label: '경험순' },
  { value: 'reviews', label: '리뷰순' },
];

export const SPECIALTIES = [
  '대형견 전문',
  '소형견 전문',
  '고령견 케어',
  '활발한 강아지',
  '조용한 강아지',
  '사회화 훈련',
  '기본 훈련',
  '산책 전문',
  '런닝 파트너',
  '야간 산책',
];

export const LANGUAGES = [
  '한국어',
  '영어',
  '일본어',
  '중국어',
];

export const CERTIFICATIONS = [
  '펫시터 자격증',
  '동물행동학 자격증',
  '응급처치 자격증',
  '펫 그루밍 자격증',
  '동물복지 자격증',
];

export const MOCK_WALKERS = [
  {
    id: '1',
    name: '김워커',
    rating: 4.9,
    reviewCount: 127,
    profileImage: 'https://via.placeholder.com/80',
    bio: '5년 경력의 전문 펫시터입니다. 모든 크기의 강아지를 사랑합니다.',
    experience: '5년',
    hourlyRate: 15000,
    isAvailable: true,
    location: '강남구',
    distance: 0.8,
    specialties: ['대형견 전문', '사회화 훈련'],
    languages: ['한국어', '영어'],
    certifications: ['펫시터 자격증', '동물행동학 자격증'],
  },
  {
    id: '2',
    name: '이산책',
    rating: 4.8,
    reviewCount: 89,
    profileImage: 'https://via.placeholder.com/80',
    bio: '활발한 강아지들과 함께 뛰어놀기를 좋아합니다.',
    experience: '3년',
    hourlyRate: 12000,
    isAvailable: true,
    location: '서초구',
    distance: 1.2,
    specialties: ['활발한 강아지', '런닝 파트너'],
    languages: ['한국어'],
    certifications: ['펫시터 자격증'],
  },
  {
    id: '3',
    name: '박펫시터',
    rating: 4.7,
    reviewCount: 203,
    profileImage: 'https://via.placeholder.com/80',
    bio: '고령견 케어 전문가입니다. 안전하고 따뜻한 케어를 제공합니다.',
    experience: '7년',
    hourlyRate: 18000,
    isAvailable: true,
    location: '송파구',
    distance: 2.1,
    specialties: ['고령견 케어', '소형견 전문'],
    languages: ['한국어', '일본어'],
    certifications: ['펫시터 자격증', '응급처치 자격증'],
  },
  {
    id: '4',
    name: '최강아지',
    rating: 4.6,
    reviewCount: 156,
    profileImage: 'https://via.placeholder.com/80',
    bio: '모든 강아지의 개성을 존중하며 맞춤형 케어를 제공합니다.',
    experience: '4년',
    hourlyRate: 14000,
    isAvailable: false,
    location: '마포구',
    distance: 1.8,
    specialties: ['기본 훈련', '사회화 훈련'],
    languages: ['한국어', '중국어'],
    certifications: ['동물행동학 자격증'],
  },
  {
    id: '5',
    name: '정야간',
    rating: 4.5,
    reviewCount: 78,
    profileImage: 'https://via.placeholder.com/80',
    bio: '야간 산책 전문가입니다. 안전한 밤 산책을 도와드립니다.',
    experience: '2년',
    hourlyRate: 16000,
    isAvailable: true,
    location: '용산구',
    distance: 0.5,
    specialties: ['야간 산책', '대형견 전문'],
    languages: ['한국어'],
    certifications: ['펫시터 자격증', '응급처치 자격증'],
  },
];
